
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-UCSBDiningCommonMenuItem","number":54,"title":"Tony ucsb dining common menu item","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/54"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Get-Post","number":53,"title":"Created HelpRequestController, added GET (index) and POST (create), and added associated tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/53"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequestTable","number":51,"title":"Added entity, repository, and json files for HelpRequest","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/51"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-RecLetter-Controller-Delete","number":50,"title":"Add delete endpoint to RecommendationRequestController","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/50"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-RecLetter-Controller-Put","number":49,"title":"Add PUT endpoint to RecommendationRequestController","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/49"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-RecLetter-Controller-Get","number":48,"title":"Added Singular Get to RecommendationRequestController","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/48"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-RecLetter-Controller","number":44,"title":"Add Rec Letter Controller & Associated Tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/44"},{"author":{"id":"MDQ6VXNlcjI2MzQ3ODk3","is_bot":false,"login":"Division7","name":"Daniel Jensen"},"headRefName":"Daniel-RecLetter","number":43,"title":"Add Recommendation Requests Entity, Repository, and DB Table","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/43"}]
