
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxNTIwMzU4","is_bot":false,"login":"SR33G33","name":"Sreeganesh Siva"},"headRefName":"Sreeganesh-MenuItemReviewTable-Controller-PUT","number":61,"title":"Sreeganesh menu item review table controller put functions and tests complete","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/61"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Delete","number":60,"title":"Added DELETE Endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/60"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Put-Edit","number":59,"title":"Added PUT endpoint for singular","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/59"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Get-Show","number":58,"title":"Added GET singular endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/58"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-UCSBOrganizations-Controller","number":57,"title":"Added UCSB Organizations Controller and Tests for this Controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/57"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-MenuItem-Controller","number":55,"title":"Tony menu item controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/55"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-UCSBDiningCommonMenuItem","number":54,"title":"Tony ucsb dining common menu item","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/54"},{"author":{"id":"U_kgDOBdHh1A","is_bot":false,"login":"jason-rodrigues","name":""},"headRefName":"Jason-HelpRequest-Get-Post","number":53,"title":"Created HelpRequestController, added GET (index) and POST (create), and added associated tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/53"}]
