
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-4
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-4
pull_requests: [{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-MenuItem-Edit","number":71,"title":"Completed Controller and Tests for Put endpoint for menuItem","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/71"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-MenuItem-GetSingle","number":70,"title":"Added Get Single Endpoint for Menuitem","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/70"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-UCSBOrganizations-DELETE","number":69,"title":"Added endpoints for DELETE","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/69"},{"author":{"id":"U_kgDOBdC-lQ","is_bot":false,"login":"Simonmann17","name":""},"headRefName":"Simon-UCSbOrganizations-Controller-GET","number":68,"title":"Added Controller and Tests for GET endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/68"},{"author":{"id":"U_kgDOBYEfQA","is_bot":false,"login":"GuBinhti","name":""},"headRefName":"Tony-MenuItem-GetShow","number":67,"title":"Added Endpoints for Get and Show MenuItems Tony","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-4/pull/67"}]
